/***********************************************
*                                              *
*     Combined Reducers for main application   *
*     Generated by ts2redux                    *
*                                              *
***********************************************/
import * as redux from 'redux';
import { IIncModel, IncModelReducer } from './IncModel';
import { ISimpleModel, SimpleModelReducer } from './SimpleModel';
import { ITestModel, TestModelReducer } from './TestModel';
import { ITodoList, TodoListReducer } from './TodoList';
import { IUserState, UserStateReducer } from './UserState';
export interface IState {
  IncModel: IIncModel
  SimpleModel: ISimpleModel
  TestModel: ITestModel
  TodoList: ITodoList
  UserState: IUserState
}
export const reducers = redux.combineReducers<IState>({
  IncModel: IncModelReducer,
  SimpleModel: SimpleModelReducer,
  TestModel: TestModelReducer,
  TodoList: TodoListReducer,
  UserState: UserStateReducer,
})
