export const actionsEnums = {
  ACTION_SHOPCARTMODEL_UPDATEITEMS : "ACTION_SHOPCARTMODEL_UPDATEITEMS",
  RUNNING_FETCHALL : "RUNNING_FETCHALL",
  ERROR_FETCHALL : "ERROR_FETCHALL",
  SUCCESS_FETCHALL : "SUCCESS_FETCHALL",
  ACTION_SHOPCARTMODEL_ADDITEM : "ACTION_SHOPCARTMODEL_ADDITEM",
  RUNNING_REQUSTADDNEWITEM : "RUNNING_REQUSTADDNEWITEM",
  ERROR_REQUSTADDNEWITEM : "ERROR_REQUSTADDNEWITEM",
  SUCCESS_REQUSTADDNEWITEM : "SUCCESS_REQUSTADDNEWITEM",
  RUNNING_ANYFN : "RUNNING_ANYFN",
  ERROR_ANYFN : "ERROR_ANYFN",
  SUCCESS_ANYFN : "SUCCESS_ANYFN",
}
